### ISSUE TITLE
Null Reference exception at startup

### ISSUE THREAD

**Issue by DomDom3333** [flarive/Neumorphism.Avalonia#34]
I get the following exception when trying to start the project

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Avalonia.Themes.Neumorphism.NeumorphismTheme.OnPropertyChanged(AvaloniaPropertyChangedEventArgs change)
   at Avalonia.AvaloniaObject.OnPropertyChangedCore(AvaloniaPropertyChangedEventArgs change)
   at Avalonia.AvaloniaObject.RaisePropertyChanged[T](AvaloniaProperty`1 property, Optional`1 oldValue, BindingValue`1 newValue, BindingPriority priority, Boolean isEffectiveValue)
   at Avalonia.PropertyStore.EffectiveValue`1.SetAndRaiseCore(ValueStore owner, StyledProperty`1 property, T value, BindingPriority priority, Boolean isOverriddenCurrentValue, Boolean isCoercedDefaultValue)
   at Avalonia.PropertyStore.EffectiveValue`1.SetLocalValueAndRaise(ValueStore owner, StyledProperty`1 property, T value)
   at Avalonia.PropertyStore.ValueStore.SetLocalValue[T](StyledProperty`1 property, T value)
   at Avalonia.PropertyStore.ValueStore.SetValue[T](StyledProperty`1 property, T value, BindingPriority priority)
   at Avalonia.AvaloniaObject.SetValue[T](StyledProperty`1 property, T value, BindingPriority priority)
   at Avalonia.Themes.Neumorphism.NeumorphismTheme.set_PrimaryColor(PrimaryColor value)
   at RacingStatsSync.App.!XamlIlPopulate(IServiceProvider, App) in M:\Software Projects\Race Control\RaceControlClient\RacingStatsSync\App.axaml:line 8
   at RacingStatsSync.App.!XamlIlPopulateTrampoline(App)
   at RacingStatsSync.App..ctor()
   at System.RuntimeType.CreateInstanceOfT()
```

After a little bit of debugging ive narrowed it down (i think) to accessing Application.Current in the OnPropertyChanged here.

```
protected override void OnPropertyChanged(AvaloniaPropertyChangedEventArgs change)
    {
      base.OnPropertyChanged(change);
      if (change.Property == (AvaloniaProperty) NeumorphismTheme.PrimaryColorProperty)
      {
        Color color1 = SwatchHelper.Lookup[(MaterialColor) this.PrimaryColor];
        Color color2 = color1.Lighten();
        Color color3 = color1;
        Color color4 = color1.Darken();
        Application.Current.Resources[(object) "PrimaryHueLightBrush"] = (object) color2;
        Application.Current.Resources[(object) "PrimaryHueMidBrush"] = (object) color3;
        Application.Current.Resources[(object) "PrimaryHueDarkBrush"] = (object) color4;
        Application.Current.Resources[(object) "PrimaryHueLightForegroundBrush"] = (object) Color.FromRgb(byte.MaxValue, byte.MaxValue, byte.MaxValue);
        Application.Current.Resources[(object) "PrimaryHueMidForegroundBrush"] = (object) Color.FromRgb(byte.MaxValue, byte.MaxValue, byte.MaxValue);
        Application.Current.Resources[(object) "PrimaryHueDarkForegroundBrush"] = (object) Color.FromRgb(byte.MaxValue, byte.MaxValue, byte.MaxValue);
      }
      else if (change.Property == (AvaloniaProperty) NeumorphismTheme.SecondaryColorProperty)
      {
        Color color5 = SwatchHelper.Lookup[(MaterialColor) this.SecondaryColor];
        Color color6 = color5.Lighten();
        Color color7 = color5;
        Color color8 = color5.Darken();
        Application.Current.Resources[(object) "SecondaryHueLightBrush"] = (object) color6;
        Application.Current.Resources[(object) "SecondaryHueMidBrush"] = (object) color7;
        Application.Current.Resources[(object) "SecondaryHueDarkBrush"] = (object) color8;
        Application.Current.Resources[(object) "SecondaryHueLightForegroundBrush"] = (object) Color.FromRgb(byte.MaxValue, byte.MaxValue, byte.MaxValue);
        Application.Current.Resources[(object) "SecondaryHueMidForegroundBrush"] = (object) Color.FromRgb(byte.MaxValue, byte.MaxValue, byte.MaxValue);
        Application.Current.Resources[(object) "SecondaryHueDarkForegroundBrush"] = (object) Color.FromRgb(byte.MaxValue, byte.MaxValue, byte.MaxValue);
      }
      else
      {
        if (!(change.Property == (AvaloniaProperty) NeumorphismTheme.BaseThemeProperty))
          return;
        if (this.BaseTheme == ApplicationTheme.Dark)
          Application.Current.SetValue<ThemeVariant>(ThemeVariantScope.ActualThemeVariantProperty, ThemeVariant.Dark);
        else
          Application.Current.SetValue<ThemeVariant>(ThemeVariantScope.ActualThemeVariantProperty, ThemeVariant.Light);
      }
    }
    ```
    
    This is purely based on de-compilation debugging and unfortunately i cant say where in the code base the error lies or how to fix it. 
    Am i doing something wrong or is this an actual bug?

**Comment by DomDom3333** [comment]
I solved the problem (somewhat). After some trying around I created a new project. No luck. I saw there are different templates tho so I tried the MVVM template and there you go. So I transferred my whole project to MVVM, applied the theme, didn't like the result and didn't end up using it after all. But I'm on MVVM now so there's that.
